server:
  port: 8000
spring:
  application:
    name: microservice-clients
eureka:
  client:
    serviceUrl:   
      defaultZone: http://localhost:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    virtual-host-name: microservice-clientss

